### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by dizguy** [Jmandarino/Disney-Reservation-Checker#1]
Hi, I've got Twilio and Selenium installed, but when I try to run or compile the script, I get two errors:

line 322 in <module>
get_Settings() # set global variables for texting service

line 99 in get_settings
if data["to_phone_number"]:
UnboundLocalError: local variable 'data' referenced before assignment

Appreciate any help you can offer - thank you!

**Comment by Jmandarino** [comment]
Hi @dizguy, 

What is most likely happening is you didn't create an **"account.json"** file in your main directory.

I just pushed an update to fix this, like the readme says you should have your sensitive data in a file called **"accounts.json"**.

Please repull or update the name to "account.json" (note future versions of this script will use "account**s**.json"

Let me know if this fixes your issue!
